### ISSUE TITLE
Root volume using largest volume number on AWS with some local storage instance type like c5d and m5d

### ISSUE THREAD

**Issue by davidshtian** [awsmarketplace/debian-cloud-images#1]
When using debian 10 system on AWS using some local storage instance type like c5d and m5d, the root volume is using the largest volume number (like nvme2n1 on m5d.4xlarge), but not the smallest number (like nvme0n1 on m5d.4xlarge), shown as below:

```
$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
nvme0n1      259:0    0 279.4G  0 disk 
nvme1n1      259:1    0 279.4G  0 disk 
nvme2n1      259:2    0     8G  0 disk 
|-nvme2n1p1  259:3    0   7.9G  0 part /
|-nvme2n1p14 259:4    0     3M  0 part 
`-nvme2n1p15 259:5    0   124M  0 part /boot/efi
```
The system info is:

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

This will impact the automation shell script like to format volume, is there any solution to fix this? 

Kindly looking forward to your reply. Thanks~

**Comment by NeverMin** [comment]
Hi @davidshtian , thank you for your comment, but this repo just a mirror from debian, please move this issue to [debian.org](https://salsa.debian.org/cloud-team/debian-cloud-images/-/issues)
